/////////////////////////
/* ARREGLO DE PERSONAS */
/////////////////////////
var personas = [
    {
        "id": 1,
        "nombre": "Alejandro",
        "apellidoPaterno": "Delgado",
        "apellidoMaterno": "Cardona",
        "genero": "Masculino",
        "fechaNacimiento": "2003-04-23",
        "rfc": "DECA0304238C6",
        "curp": "DECA030423HGTLRLA8",
        "domicilio": "Bari 202",
        "codigoPostal": "37278",
        "ciudad": "Leon",
        "estado": "Guanajuato",
        "telefono": "4772285062",
        "foto": "foto1",
        "fechaIngreso": "2022-09-05"
    },
    {
        "id": 2,
        "nombre": "María",
        "apellidoPaterno": "García",
        "apellidoMaterno": "López",
        "genero": "Femenino",
        "fechaNacimiento": "1995-08-12",
        "rfc": "GALM950812BG1",
        "curp": "GALM950812MDFRPL09",
        "domicilio": "Juárez 123",
        "codigoPostal": "55010",
        "ciudad": "México",
        "estado": "Ciudad de México",
        "telefono": "5512345678",
        "foto": "foto2",
        "fechaIngreso": "2021-03-18"
    },
    {
        "id": 3,
        "nombre": "Carlos",
        "apellidoPaterno": "Sánchez",
        "apellidoMaterno": "Martínez",
        "genero": "Masculino",
        "fechaNacimiento": "1988-11-05",
        "rfc": "SACM881105HJ7",
        "curp": "SACM881105HDFRTR02",
        "domicilio": "Revolución 456",
        "codigoPostal": "64040",
        "ciudad": "Monterrey",
        "estado": "Nuevo León",
        "telefono": "8187654321",
        "foto": "foto3",
        "fechaIngreso": "2020-10-02"
    },
    {
        "id": 4,
        "nombre": "Ana",
        "apellidoPaterno": "López",
        "apellidoMaterno": "Guzmán",
        "genero": "Femenino",
        "fechaNacimiento": "2000-02-18",
        "rfc": "LOGA000218GR9",
        "curp": "LOGA000218MDFZNS04",
        "domicilio": "Hidalgo 789",
        "codigoPostal": "80020",
        "ciudad": "Culiacán",
        "estado": "Sinaloa",
        "telefono": "6679876543",
        "foto": "foto4",
        "fechaIngreso": "2023-01-15"
    },
    {
        "id": 5,
        "nombre": "Javier",
        "apellidoPaterno": "Ramírez",
        "apellidoMaterno": "Díaz",
        "genero": "Masculino",
        "fechaNacimiento": "1992-06-30",
        "rfc": "Radj920630IE3",
        "curp": "Radj920630HDFXZV01",
        "domicilio": "Gómez 567",
        "codigoPostal": "45050",
        "ciudad": "Guadalajara",
        "estado": "Jalisco",
        "telefono": "3338765432",
        "foto": "foto5",
        "fechaIngreso": "2022-05-09"
    },
    {
        "id": 6,
        "nombre": "Laura",
        "apellidoPaterno": "Hernández",
        "apellidoMaterno": "Luna",
        "genero": "Femenino",
        "fechaNacimiento": "1987-09-22",
        "rfc": "HELL870922JH6",
        "curp": "HELL870922MDFZLD03",
        "domicilio": "Callejón 345",
        "codigoPostal": "21010",
        "ciudad": "Puebla",
        "estado": "Puebla",
        "telefono": "2227654321",
        "foto": "foto6",
        "fechaIngreso": "2021-08-14"
    },
    {
        "id": 7,
        "nombre": "David",
        "apellidoPaterno": "Morales",
        "apellidoMaterno": "Castillo",
        "genero": "Masculino",
        "fechaNacimiento": "1999-03-11",
        "rfc": "MOCD990311KU0",
        "curp": "MOCD990311HDFRST05",
        "domicilio": "Morelos 678",
        "codigoPostal": "62000",
        "ciudad": "Cuernavaca",
        "estado": "Morelos",
        "telefono": "7776543210",
        "foto": "foto7",
        "fechaIngreso": "2022-11-20"
    },
    {
        "id": 8,
        "nombre": "Fernanda",
        "apellidoPaterno": "Pérez",
        "apellidoMaterno": "Juárez",
        "genero": "Femenino",
        "fechaNacimiento": "1996-12-08",
        "rfc": "PEJF961208GY2",
        "curp": "PEJF961208MDFRBN06",
        "domicilio": "Madero 789",
        "codigoPostal": "80050",
        "ciudad": "Chihuahua",
        "estado": "Chihuahua",
        "telefono": "6148765432",
        "foto": "foto8",
        "fechaIngreso": "2023-06-10"
    },
    {
        "id": 9,
        "nombre": "Luis",
        "apellidoPaterno": "González",
        "apellidoMaterno": "Vargas",
        "genero": "Masculino",
        "fechaNacimiento": "2001-07-17",
        "rfc": "GOVL010717IK7",
        "curp": "GOVL010717HDFRKP07",
        "domicilio": "Zaragoza 234",
        "codigoPostal": "36000",
        "ciudad": "Guanajuato",
        "estado": "Guanajuato",
        "telefono": "4737654321",
        "foto": "foto9",
        "fechaIngreso": "2022-04-25"
    },
    {
        "id": 10,
        "nombre": "Alejandra Del Rocío",
        "apellidoPaterno": "Cardona",
        "apellidoMaterno": "Guerra",
        "genero": "Femenino",
        "fechaNacimiento": "1967-10-27",
        "rfc": "CAGX6710277J6",
        "curp": "CXGA671027MCLRRL09",
        "domicilio": "Bari 202",
        "codigoPostal": "37278",
        "ciudad": "Leon",
        "estado": "Guanajuato",
        "telefono": "4772256511",
        "foto": "foto10",
        "fechaIngreso": "2005-09-01"
    },
    {
        "id": 11,
        "nombre": "Sofía",
        "apellidoPaterno": "Martínez",
        "apellidoMaterno": "Sánchez",
        "genero": "Femenino",
        "fechaNacimiento": "1998-03-25",
        "rfc": "MASO980325IT4",
        "curp": "MASO980325MDFRQS09",
        "domicilio": "Allende 123",
        "codigoPostal": "37000",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4775678901",
        "foto": "foto11",
        "fechaIngreso": "2022-08-05"
    },
    {
        "id": 12,
        "nombre": "Eduardo",
        "apellidoPaterno": "Luna",
        "apellidoMaterno": "Rodríguez",
        "genero": "Masculino",
        "fechaNacimiento": "1990-12-10",
        "rfc": "LURE901210JW6",
        "curp": "LURE901210HDFRVD04",
        "domicilio": "Hidalgo 456",
        "codigoPostal": "62080",
        "ciudad": "Cuernavaca",
        "estado": "Morelos",
        "telefono": "7771234567",
        "foto": "foto12",
        "fechaIngreso": "2021-07-02"
    },
    {
        "id": 13,
        "nombre": "Valentina",
        "apellidoPaterno": "González",
        "apellidoMaterno": "Hernández",
        "genero": "Femenino",
        "fechaNacimiento": "2002-09-15",
        "rfc": "GOHV020915MN0",
        "curp": "GOHV020915MDFRVQ05",
        "domicilio": "Juárez 789",
        "codigoPostal": "55020",
        "ciudad": "México",
        "estado": "Ciudad de México",
        "telefono": "5523456789",
        "foto": "foto13",
        "fechaIngreso": "2023-03-10"
    },
    {
        "id": 14,
        "nombre": "Juan",
        "apellidoPaterno": "Ramírez",
        "apellidoMaterno": "Gómez",
        "genero": "Masculino",
        "fechaNacimiento": "1985-07-08",
        "rfc": "RAGJ850708CV7",
        "curp": "RAGJ850708HDFRPS06",
        "domicilio": "Reforma 567",
        "codigoPostal": "66000",
        "ciudad": "Monterrey",
        "estado": "Nuevo León",
        "telefono": "8182345678",
        "foto": "foto14",
        "fechaIngreso": "2020-11-15"
    },
    {
        "id": 15,
        "nombre": "Isabella",
        "apellidoPaterno": "Sánchez",
        "apellidoMaterno": "Flores",
        "genero": "Femenino",
        "fechaNacimiento": "1993-04-28",
        "rfc": "SAFI9304285X8",
        "curp": "SAFI930428MDFRVB07",
        "domicilio": "Zapata 234",
        "codigoPostal": "36020",
        "ciudad": "Guanajuato",
        "estado": "Guanajuato",
        "telefono": "4738765432",
        "foto": "foto15",
        "fechaIngreso": "2022-09-20"
    },
    {
        "id": 16,
        "nombre": "Fernando",
        "apellidoPaterno": "Pérez",
        "apellidoMaterno": "Mendoza",
        "genero": "Masculino",
        "fechaNacimiento": "1986-10-31",
        "rfc": "PEMF861031EJ3",
        "curp": "PEMF861031HDFRDF08",
        "domicilio": "Revolución 789",
        "codigoPostal": "80060",
        "ciudad": "Chihuahua",
        "estado": "Chihuahua",
        "telefono": "6147654321",
        "foto": "foto16",
        "fechaIngreso": "2021-12-28"
    },
    {
        "id": 17,
        "nombre": "Mariano",
        "apellidoPaterno": "López",
        "apellidoMaterno": "Ortega",
        "genero": "Masculino",
        "fechaNacimiento": "1997-11-20",
        "rfc": "LOMM971120EK1",
        "curp": "LOMM971120HDFRMN09",
        "domicilio": "Madero 345",
        "codigoPostal": "21020",
        "ciudad": "Puebla",
        "estado": "Puebla",
        "telefono": "2228765432",
        "foto": "foto17",
        "fechaIngreso": "2023-04-12"
    },
    {
        "id": 18,
        "nombre": "Diana",
        "apellidoPaterno": "Hernández",
        "apellidoMaterno": "García",
        "genero": "Femenino",
        "fechaNacimiento": "2004-01-12",
        "rfc": "HEGD0401124T5",
        "curp": "HEGD040112MDFRHN06",
        "domicilio": "Obregón 678",
        "codigoPostal": "37020",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4776789012",
        "foto": "foto18",
        "fechaIngreso": "2023-02-05"
    },
    {
        "id": 19,
        "nombre": "Roberto",
        "apellidoPaterno": "García",
        "apellidoMaterno": "Torres",
        "genero": "Masculino",
        "fechaNacimiento": "2000-08-05",
        "rfc": "GATR000805RP4",
        "curp": "GATR000805HDFRRB05",
        "domicilio": "Zaragoza 456",
        "codigoPostal": "55030",
        "ciudad": "México",
        "estado": "Ciudad de México",
        "telefono": "5545678901",
        "foto": "foto19",
        "fechaIngreso": "2022-07-15"
    },
    {
        "id": 20,
        "nombre": "Camila",
        "apellidoPaterno": "Luna",
        "apellidoMaterno": "Mendoza",
        "genero": "Femenino",
        "fechaNacimiento": "1991-05-17",
        "rfc": "LUMC910517NB2",
        "curp": "LUMC910517MDFRCM08",
        "domicilio": "Independencia 789",
        "codigoPostal": "66050",
        "ciudad": "Monterrey",
        "estado": "Nuevo León",
        "telefono": "8183456789",
        "foto": "foto20",
        "fechaIngreso": "2021-10-25"
    }
];

/////////////////////////
/* ARREGLO DE CLIENTES */
/////////////////////////
var clientes = [
    {
        "id": 22080011,
        "email": "sofiams98@gmail.com",
        "estatus": 1,
        "persona": personas[10]
    },
    {
        "id": 21070012,
        "email": "eduardolr90@gmail.com",
        "estatus": 1,
        "persona": personas[11]
    },
    {
        "id": 22080012,
        "email": "valentinagh02@gmail.com",
        "estatus": 1,
        "persona": personas[12]
    },
    {
        "id": 22080013,
        "email": "juanrg85@gmail.com",
        "estatus": 1,
        "persona": personas[13]
    },
    {
        "id": 22080014,
        "email": "isabellasf93@gmail.com",
        "estatus": 1,
        "persona": personas[14]
    },
    {
        "id": 22080015,
        "email": "fernandopm86@gmail.com",
        "estatus": 1,
        "persona": personas[15]
    },
    {
        "id": 22080016,
        "email": "marianolo97@gmail.com",
        "estatus": 1,
        "persona": personas[16]
    },
    {
        "id": 22080017,
        "email": "dianahg04@gmail.com",
        "estatus": 1,
        "persona": personas[17]
    },
    {
        "id": 22080018,
        "email": "robertogt00@gmail.com",
        "estatus": 1,
        "persona": personas[18]
    },
    {
        "id": 22080019,
        "email": "camilalm91@gmail.com",
        "estatus": 1,
        "persona": personas[19]
    }
];

///////////////////////////
/* ARREGLO DE SUCURSALES */
///////////////////////////
var sucursales = [
    {
        "id": 1,
        "nombre": "Matriz",
        "titular": "Juan Pérez",
        "rfc": "PEJL850920ABC12",
        "domicilio": "Av. Reforma 456",
        "colonia": "Centro",
        "codigoPostal": "37000",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4772345678",
        "latitud": "21.1589",
        "longitud": "-101.6544",
        "estatus": 1,
    },
    {
        "id": 2,
        "nombre": "Centro",
        "titular": "Alejandra González",
        "rfc": "GOAL850920XYZ12",
        "domicilio": "Av. Juárez 789",
        "colonia": "Centro",
        "codigoPostal": "37000",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4773456789",
        "latitud": "21.1234",
        "longitud": "-101.6789",
        "estatus": 1,
    },
    {
        "id": 3,
        "nombre": "Centro Max",
        "titular": "Ricardo Martínez",
        "rfc": "MARR850920ABC12",
        "domicilio": "Blvd. Adolfo López Mateos 123",
        "colonia": "Predio San Carlos",
        "codigoPostal": "37270",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4774567890",
        "latitud": "21.1605",
        "longitud": "-101.7014",
        "estatus": 1,
    },
    {
        "id": 4,
        "nombre": "Plaza Mayor",
        "titular": "Mónica Hernández",
        "rfc": "HEMM850920XYZ12",
        "domicilio": "Blvd. José María Morelos 456",
        "colonia": "Fraccionamiento El Mayor",
        "codigoPostal": "37510",
        "ciudad": "León",
        "estado": "Guanajuato",
        "telefono": "4775678901",
        "latitud": "21.1150",
        "longitud": "-101.7002",
        "estatus": 1,
    },
    {
        "id": 5,
        "nombre": 'Sucursal A',
        "titular": 'María López',
        "rfc": 'LOHS850920XYZ12',
        "domicilio": 'Av. Principal 123',
        "colonia": 'Centro',
        "codigoPostal": 'Ciudad de México',
        "ciudad": 'Ciudad de México',
        "estado": '12345',
        "telefono": '5551234567',
        "latitud": '19.4326',
        "longitud": '-99.1332',
        "estatus": 1,
    },
    {
        "id": 6,
        "nombre": "Sucursal B",
        "titular": "Carlos Martínez",
        "rfc": "MAGC010210PQR78",
        "domicilio": "Calle Secundaria 456",
        "colonia": "Bella Vista",
        "ciudad": "Monterrey",
        "estado": "Nuevo León",
        "codigoPostal": "54321",
        "telefono": "5559876543",
        "longitud": "-100.3161",
        "latitud": "25.6866",
        "estatus": 1,
    },
    {
        "id": 7,
        "nombre": "Sucursal C",
        "titular": "Ana Pérez",
        "rfc": "PEAR981105XYZ12",
        "domicilio": "Carrera 789",
        "colonia": "Juárez",
        "ciudad": "Puebla",
        "estado": "Puebla",
        "codigoPostal": "54321",
        "telefono": "5552345678",
        "longitud": "-98.2063",
        "latitud": "19.0414",
        "estatus": 1,
    },
    {
        "id": 8,
        "nombre": "Sucursal D",
        "titular": "Luis Sánchez",
        "rfc": "SAVL820730ABC56",
        "domicilio": "Avenida Principal 234",
        "colonia": "San Miguel",
        "ciudad": "Tijuana",
        "estado": "Baja California",
        "codigoPostal": "67890",
        "telefono": "5556789012",
        "longitud": "-117.0382",
        "latitud": "32.5149",
        "estatus": 1,
    },
    {
        "id": 9,
        "nombre": "Sucursal E",
        "titular": "Laura González",
        "rfc": "GOLF950318DEF89",
        "domicilio": "Calle Ocampo 567",
        "colonia": "Nueva Era",
        "ciudad": "Mérida",
        "estado": "Yucatán",
        "codigoPostal": "43210",
        "telefono": "5553456789",
        "longitud": "-89.6237",
        "latitud": "20.9676",
        "estatus": 1,
    },
    {
        "id": 10,
        "nombre": "Sucursal F",
        "titular": "Javier Ruíz",
        "rfc": "RULJ771203LMN12",
        "domicilio": "Boulevard 890",
        "colonia": "Los Pinos",
        "ciudad": "Cancún",
        "estado": "Quintana Roo",
        "codigoPostal": "54321",
        "telefono": "5554567890",
        "longitud": "-86.8515",
        "latitud": "21.1619",
        "estatus": 1,
    }
];

//////////////////////////
/* ARREGLO DE EMPLEADOS */
//////////////////////////
var empleados = [
    {
        "id": personas[1].id,
        "codigo": "20100003",
        "puesto": "Administrador Central",
        "salario": "10000",
        "activo": 1,
        "persona": personas[1],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[2].id,
        "codigo": "23010004",
        "puesto": "Administrador Sucursal",
        "salario": "10000",
        "activo": 1,
        "persona": personas[2],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[3].id,
        "codigo": "22050005",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[3],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[4].id,
        "codigo": "21080006",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[4],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[5].id,
        "codigo": "22020007",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[5],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[6].id,
        "codigo": "23080008",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[6],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[7].id,
        "codigo": "22060009",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[7],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[8].id,
        "codigo": "21090010",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[8],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[9].id,
        "codigo": "22040011",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[9],
        "sucursal": sucursales[0]
    },
    {
        "id": personas[10].id,
        "codigo": "23070012",
        "puesto": "Empleado",
        "salario": "10000",
        "activo": 1,
        "persona": personas[10],
        "sucursal": sucursales[0]
    }

];

/////////////////////////
/* ARREGLO DE USUARIOS */
/////////////////////////
var usuarios = [
    {
        "usuario": "admin",
        "contrasena": "admin",
        "rol": "ADMC",
        "empleado": empleados[0]
    },
    {
        "usuario": "admins",
        "contrasena": "admins",
        "rol": "ADMS",
        "empleado": empleados[1]
    },
    {
        "usuario": empleados[2].codigo,
        "contrasena": empleados[2].codigo,
        "rol": "EMPS",
        "empleado": empleados[2]
    },
    {
        "usuario": empleados[3].codigo,
        "contrasena": empleados[3].codigo,
        "rol": "EMPS",
        "empleado": empleados[3]
    },
    {
        "usuario": empleados[4].codigo,
        "contrasena": empleados[4].codigo,
        "rol": "EMPS",
        "empleado": empleados[4]
    },
    {
        "usuario": empleados[5].codigo,
        "contrasena": empleados[5].codigo,
        "rol": "EMPS",
        "empleado": empleados[5]
    },
    {
        "usuario": empleados[6].codigo,
        "contrasena": empleados[6].codigo,
        "rol": "EMPS",
        "empleado": empleados[6]
    },
    {
        "usuario": empleados[7].codigo,
        "contrasena": empleados[7].codigo,
        "rol": "EMPS",
        "empleado": empleados[7]
    },
    {
        "usuario": empleados[8].codigo,
        "contrasena": empleados[8].codigo,
        "rol": "EMPS",
        "empleado": empleados[8]
    },
    {
        "usuario": empleados[9].codigo,
        "contrasena": empleados[9].codigo,
        "rol": "EMPS",
        "empleado": empleados[9]
    }
];

//////////////////////////
/* ARREGLO DE PRODUCTOS */
//////////////////////////
var productos = [
    {
        "idProducto": 1,
        "nombre": "Donepecilo",
        "nombreGenerico": "Donepecilo, Clorhidrato de",
        "formaFarmaceutica": "tableta",
        "unidadMedida": "Tableta",
        "presentacion": "Envase con 14 tabletas.",
        "principalIndicacion": "Enfermedad de Alzheimer.",
        "contraindicaciones": "Hipersensibilidad al fármaco o a los derivados de piperidina.",
        "concentracion": "10 mg",
        "unidadesEnvase": 14,
        "precioCompra": 466.9,
        "precioVenta": 547,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 2,
        "nombre": "Etambutol",
        "nombreGenerico": "Etambutol, Clorhidrato de",
        "formaFarmaceutica": "tableta",
        "unidadMedida": "Tableta",
        "presentacion": "Envase con 50 tabletas.",
        "principalIndicacion": "Tuberculosis.",
        "contraindicaciones": "Hipersensibilidad al fármaco, neuritis óptica y en menores de 12 años.",
        "concentracion": "400 mg",
        "unidadesEnvase": 50,
        "precioCompra": 65.71,
        "precioVenta": 210,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 3,
        "nombre": "Efavirenz",
        "nombreGenerico": "Efavirenz",
        "formaFarmaceutica": "comprimido recubierto",
        "unidadMedida": "Comprimido",
        "presentacion": "Envase con 30 comprimidos recubiertos.",
        "principalIndicacion": "Infección por Virus de Inmunodeficiencia Humana (VIH), en combinación con otros antirretrovirales.",
        "contraindicaciones": "Hipersensibilidad al fármaco.",
        "concentracion": "600 mg",
        "unidadesEnvase": 30,
        "precioCompra": 134.19,
        "precioVenta": 254,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 4,
        "nombre": "Ciprofibrato",
        "nombreGenerico": "Ciprofibrato",
        "formaFarmaceutica": "cápsula o tableta",
        "unidadMedida": "Cápsula",
        "presentacion": "Envase con 30 cápsulas o tabletas.",
        "principalIndicacion": "Hiperlipidemias tipo IIb y IV.",
        "contraindicaciones": "Hipersensibilidad al fármaco. Insuficiencia hepática o renal. Embarazo y lactancia.",
        "concentracion": "100 mg",
        "unidadesEnvase": 30,
        "precioCompra": 551.32,
        "precioVenta": 665,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 5,
        "nombre": "Lidocaína",
        "nombreGenerico": "Lidocaína, Clorhidrato de",
        "formaFarmaceutica": "gel",
        "unidadMedida": "Mililitro",
        "presentacion": "Envase con 20 ml.",
        "principalIndicacion": "Anestesia local.",
        "contraindicaciones": "Hipersensibilidad conocida a anestésicos locales de tipo amida o a los otros componentes de la fórmula.",
        "concentracion": "20 mg / ml",
        "unidadesEnvase": 20,
        "precioCompra": 28.86,
        "precioVenta": 306,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 6,
        "nombre": "Ambroxol",
        "nombreGenerico": "Ambroxol, Clorhidrato de",
        "formaFarmaceutica": "solución",
        "unidadMedida": "Mililitro",
        "presentacion": "Envase con 120 ml y dosificador.",
        "principalIndicacion": "Bronquitis",
        "contraindicaciones": "Hipersensibilidad al fármaco.",
        "concentracion": "300 mg/100 ml",
        "unidadesEnvase": 120,
        "precioCompra": 215.79,
        "precioVenta": 277,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 7,
        "nombre": "Metronidazol",
        "nombreGenerico": "Metronidazol",
        "formaFarmaceutica": "óvulo o tableta vaginal",
        "unidadMedida": "Óvulo",
        "presentacion": "Envase con 10 óvulos o tabletas.",
        "principalIndicacion": "Tricomoniasis vaginal",
        "contraindicaciones": "Hipersensibilidad al fármaco.",
        "concentracion": "500 mg",
        "unidadesEnvase": 10,
        "precioCompra": 616.72,
        "precioVenta": 973,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 8,
        "nombre": "Nitrofural",
        "nombreGenerico": "Nitrofural",
        "formaFarmaceutica": "óvulo",
        "unidadMedida": "Óvulo",
        "presentacion": "Envase con 6 óvulos.",
        "principalIndicacion": "Vaginitis bacteriana",
        "contraindicaciones": "Hipersensibilidad al fármaco.",
        "concentracion": "6 mg",
        "unidadesEnvase": 6,
        "precioCompra": 117.98,
        "precioVenta": 213,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 9,
        "nombre": "Ibuprofeno",
        "nombreGenerico": "Ibuprofeno",
        "formaFarmaceutica": "cápsula",
        "unidadMedida": "Miligramo",
        "presentacion": "Envase con 30 cápsulas",
        "principalIndicacion": "Dolor de leve a moderado.",
        "contraindicaciones": "NINGUNA",
        "concentracion": "400 mg",
        "unidadesEnvase": 30,
        "precioCompra": 29.3,
        "precioVenta": 537,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    },
    {
        "idProducto": 10,
        "nombre": "Montelukast",
        "nombreGenerico": "Montelukast sódico",
        "formaFarmaceutica": "comprimido recubierto",
        "unidadMedida": "Comprimido",
        "presentacion": "Envase con 30 comprimidos.",
        "principalIndicacion": "Asma bronquial",
        "contraindicaciones": "Hipersensibilidad al fármaco. No es de primera elección en el ataque agudo de asma, No se recomienda en menores de 6 años, ni durante la lactancia.",
        "concentracion": "10 mg",
        "unidadesEnvase": 30,
        "precioCompra": 592.51,
        "precioVenta": 686,
        "foto": "",
        "rutaFoto": "",
        "codigoBarras": "",
        "estatus": 1
    }
];

///////////////////////
/* ARREGLO DE VENTAS */
///////////////////////
